"""Local OSA instance management — init, start, stop, logs, status."""

from __future__ import annotations

import importlib.resources
import re
import secrets
import subprocess
from pathlib import Path

import yaml

OSA_IMAGE_VERSION = "v0.0.1"


class InstanceError(Exception):
    """Raised when a local instance operation fails."""


def _generate_secret(length: int = 32) -> str:
    return secrets.token_urlsafe(length)


def _compose_template_path() -> Path:
    ref = importlib.resources.files("osa.cli.templates").joinpath("docker-compose.yml")
    return Path(str(ref))


def _read_project_name(project_dir: Path) -> str:
    config_path = project_dir / "osa.yaml"
    if not config_path.exists():
        raise InstanceError(
            "osa.yaml not found. Run `osa init` first or cd into your project directory."
        )
    data = yaml.safe_load(config_path.read_text())
    name = data.get("name", project_dir.name)
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


_ENV_TEMPLATE = """\
# OSA instance configuration — generated by `osa init`
# Edit as needed. Do not commit to version control.

# === Image Version ===
OSA_IMAGE_VERSION={image_version}

# === Database ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD={postgres_password}
POSTGRES_DB=osa

# === Logging ===
LOG_LEVEL=INFO

# === Authentication ===
JWT_SECRET={jwt_secret}

# ORCID credentials (register at https://orcid.org/developer-tools)
ORCID_CLIENT_ID=
ORCID_CLIENT_SECRET=
ORCID_SANDBOX=true
ORCID_ADMINS=[]
"""

_OSA_YAML_TEMPLATE = """\
name: "{name}"
domain: "localhost"

auth:
  providers:
    orcid:
      client_id: ${{ORCID_CLIENT_ID}}
      client_secret: ${{ORCID_CLIENT_SECRET}}
  base_role: "DEPOSITOR"
"""

_GITIGNORE_LINES = [".data/", ".env", ".osa/"]


def init_project(
    *,
    project_dir: Path,
    name: str | None = None,
    force: bool = False,
) -> Path:
    """Scaffold a new OSA project directory.

    Returns the project directory path.
    """
    project_dir.mkdir(parents=True, exist_ok=True)

    if (project_dir / "osa.yaml").exists() and not force:
        raise InstanceError("Project already initialized. Use --force to overwrite.")

    resolved_name = name or project_dir.name

    # Write osa.yaml
    (project_dir / "osa.yaml").write_text(_OSA_YAML_TEMPLATE.format(name=resolved_name))

    # Write .env with generated secrets
    (project_dir / ".env").write_text(
        _ENV_TEMPLATE.format(
            image_version=OSA_IMAGE_VERSION,
            postgres_password=_generate_secret(16),
            jwt_secret=_generate_secret(32),
        )
    )

    # Create directories
    (project_dir / ".data").mkdir(exist_ok=True)
    (project_dir / ".osa").mkdir(exist_ok=True)

    # Write or append .gitignore
    gitignore_path = project_dir / ".gitignore"
    existing = gitignore_path.read_text() if gitignore_path.exists() else ""
    existing_lines = existing.splitlines()
    to_add = [line for line in _GITIGNORE_LINES if line not in existing_lines]
    if to_add:
        separator = "\n" if existing and not existing.endswith("\n") else ""
        gitignore_path.write_text(existing + separator + "\n".join(to_add) + "\n")

    print(f"Initialized OSA project in {project_dir}")
    print()
    print("Created:")
    print("  osa.yaml    — archive configuration")
    print("  .env        — secrets and settings (do not commit)")
    print("  .data/      — persistent data directory")
    print("  .osa/       — CLI state")
    print("  .gitignore  — ignores .data/, .env, .osa/")
    print()
    print("Next steps:")
    if project_dir.resolve() != Path.cwd().resolve():
        print(f"  cd {project_dir.name}")
    print("  osa start")

    return project_dir


def _build_compose_command(
    *,
    project_dir: Path,
    project_name: str,
    source: Path | None = None,
    profiles: list[str] | None = None,
) -> list[str]:
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "--project-directory",
        str(project_dir),
        "-f",
        str(_compose_template_path()),
    ]

    if source is not None:
        dev_override = _write_dev_override(source=source, project_dir=project_dir)
        cmd.extend(["-f", str(dev_override)])

    override_path = project_dir / "docker-compose.override.yml"
    if override_path.exists():
        cmd.extend(["-f", str(override_path)])

    for profile in profiles or []:
        cmd.extend(["--profile", profile])

    cmd.extend(["--env-file", str(project_dir / ".env")])

    return cmd


def _write_dev_override(*, source: Path, project_dir: Path) -> Path:
    source_abs = source.resolve()
    override = {
        "services": {
            "server": {
                "build": {
                    "context": str(source_abs),
                    "dockerfile": "Dockerfile",
                    "target": "builder",
                },
                "image": None,
                "volumes": [
                    f"{source_abs}:/app",
                    "/app/.venv",
                    "./osa.yaml:/app/config.yaml:ro",
                    "./.data:/data",
                ],
                "environment": {
                    "OSA_LOGGING__LEVEL": "${LOG_LEVEL:-DEBUG}",
                    "WATCHFILES_FORCE_POLLING": "true",
                },
                "entrypoint": [],
                "command": (
                    "sh -c '"
                    "/app/.venv/bin/alembic upgrade head && "
                    "/app/.venv/bin/python /app/scripts/seed.py && "
                    "/app/.venv/bin/uvicorn osa.application.api.rest.app:app "
                    "--host 0.0.0.0 --port 8000 --reload"
                    "'"
                ),
                "healthcheck": {
                    "test": [
                        "CMD",
                        "curl",
                        "--fail",
                        "http://localhost:8000/api/v1/health",
                    ],
                    "interval": "10s",
                    "timeout": "5s",
                    "start_period": "30s",
                    "retries": 3,
                },
            }
        }
    }
    dest = project_dir / ".osa" / "docker-compose.dev.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml.dump(override, default_flow_style=False, sort_keys=False))
    return dest


def start_instance(
    *,
    project_dir: Path,
    detach: bool = True,
    source: Path | None = None,
    with_ui: bool = False,
) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    profiles = ["ui"] if with_ui else []

    cmd = _build_compose_command(
        project_dir=project_dir,
        project_name=project_name,
        source=source,
        profiles=profiles,
    )

    args = [*cmd, "up"]
    if source is not None:
        args.append("--build")
    if detach:
        args.append("-d")

    result = subprocess.run(args, cwd=project_dir, text=True)
    if result.returncode != 0:
        raise InstanceError("Failed to start OSA instance.")
    return result


def stop_instance(*, project_dir: Path) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    result = subprocess.run([*cmd, "down"], cwd=project_dir, text=True)
    if result.returncode != 0:
        raise InstanceError("Failed to stop OSA instance.")
    return result


def instance_logs(
    *,
    project_dir: Path,
    follow: bool = False,
    service: str | None = None,
    tail: int | None = None,
) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    args = [*cmd, "logs"]
    if follow:
        args.append("--follow")
    if tail is not None:
        args.extend(["--tail", str(tail)])
    if service:
        args.append(service)
    return subprocess.run(args, cwd=project_dir, text=True)


def instance_status(*, project_dir: Path) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    return subprocess.run([*cmd, "ps"], cwd=project_dir, text=True)
