"""Local OSA instance management — init, start, stop, logs, status."""

from __future__ import annotations

import base64
import hashlib
import hmac
import importlib.resources
import json
import os
import re
import secrets
import subprocess
import time
from pathlib import Path

import yaml
from pydantic import BaseModel

from osa.cli.proc import run_streamed, tail
from osa.cli.ui import UI

GHCR_IMAGE = "opensciencearchive/osa"
LOCAL_SERVER_URL = "http://127.0.0.1:8000"


def fetch_latest_osa_version() -> str:
    """Fetch the latest semver tag from GHCR for the OSA server image."""
    import httpx

    token_url = f"https://ghcr.io/token?scope=repository:{GHCR_IMAGE}:pull"
    tags_url = f"https://ghcr.io/v2/{GHCR_IMAGE}/tags/list"

    try:
        token_resp = httpx.get(token_url, timeout=10)
        token_resp.raise_for_status()
        token = token_resp.json()["token"]

        tags_resp = httpx.get(
            tags_url, headers={"Authorization": f"Bearer {token}"}, timeout=10
        )
        tags_resp.raise_for_status()
        tags = tags_resp.json()["tags"]
    except (httpx.HTTPError, KeyError) as e:
        raise InstanceError(
            "Could not fetch latest OSA version from the container registry",
            hint="Use --osa-version to specify manually",
        ) from e

    semver = [t for t in tags if re.match(r"^v\d+\.\d+\.\d+$", t)]
    if not semver:
        raise InstanceError(
            "No release tags found in the container registry",
            hint="Use --osa-version to specify manually",
        )

    semver.sort(key=lambda t: tuple(int(x) for x in t[1:].split(".")))
    return semver[-1]


class InstanceError(Exception):
    """Raised when a local instance operation fails."""

    def __init__(
        self, message: str, *, cause: str | None = None, hint: str | None = None
    ) -> None:
        super().__init__(message)
        self.cause = cause
        self.hint = hint


class InitResult(BaseModel):
    """Outcome of project scaffolding, rendered by the CLI layer."""

    project_dir: Path
    created: list[tuple[str, str]]
    show_cd: bool


class ComposeService(BaseModel):
    """One row of `docker compose ps` output."""

    name: str
    state: str
    health: str
    ports: str


def _compose_template_path() -> Path:
    ref = importlib.resources.files("osa.cli.templates").joinpath("docker-compose.yml")
    return Path(str(ref))


def _read_project_name(project_dir: Path) -> str:
    config_path = project_dir / "osa.yaml"
    if not config_path.exists():
        raise InstanceError(
            "osa.yaml not found. Run `osa init` first or cd into your project directory."
        )
    data = yaml.safe_load(config_path.read_text()) or {}
    name = data.get("name", project_dir.name)
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


DEV_ADMIN_USER_ID = "00000000-0000-7000-8000-0000000000a1"
DEV_JWT_SECRET = (
    "osa-local-dev-jwt-secret-CHANGE-IN-PRODUCTION-not-suitable-for-real-use"
)


def _mint_dev_token() -> str:
    header = json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":"))
    payload = json.dumps(
        {
            "sub": DEV_ADMIN_USER_ID,
            "provider": "local",
            "external_id": "admin@osa.local",
            "aud": "authenticated",
            "iat": int(time.time()),
            "exp": int(time.time()) + 86400 * 365,
            "jti": secrets.token_hex(16),
        },
        separators=(",", ":"),
    )
    header_b64 = _b64url(header.encode())
    payload_b64 = _b64url(payload.encode())
    message = f"{header_b64}.{payload_b64}".encode()
    signature = hmac.new(DEV_JWT_SECRET.encode(), message, hashlib.sha256).digest()
    return f"{header_b64}.{payload_b64}.{_b64url(signature)}"


def _store_dev_credentials() -> None:
    """Mint a dev token signed with the well-known dev secret, store it."""
    token = _mint_dev_token()

    from osa.cli.credentials import write_credentials

    write_credentials(
        "http://127.0.0.1:8000",
        access_token=token,
        refresh_token="dev-no-refresh",
    )


_ENV_TEMPLATE = """\
# OSA instance configuration — generated by `osa init`
# Edit as needed. Do not commit to version control.

# === Database ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD=osa-local-dev-password-CHANGE-IN-PRODUCTION
POSTGRES_DB=osa

# === Logging ===
LOG_LEVEL=INFO

# === Authentication ===
# OSA_DEV_MODE=true is required for local archives: it lets the server start
# with the placeholder JWT_SECRET below and mints a SUPERADMIN dev token so
# `osa deploy` is authenticated out of the box. Set to false and supply a real
# JWT_SECRET + ORCID credentials for non-local deployments.
OSA_DEV_MODE=true
JWT_SECRET=osa-local-dev-jwt-secret-CHANGE-IN-PRODUCTION-not-suitable-for-real-use

# ORCID credentials (register at https://orcid.org/developer-tools)
ORCID_CLIENT_ID=
ORCID_CLIENT_SECRET=
ORCID_SANDBOX=true
ORCID_ADMINS=[]
"""

_OSA_YAML_TEMPLATE = """\
name: "{name}"
domain: "localhost"

auth:
  providers:
    orcid:
      client_id: ${{ORCID_CLIENT_ID}}
      client_secret: ${{ORCID_CLIENT_SECRET}}
  base_role: "DEPOSITOR"
"""

_GITIGNORE_LINES = [".data/", ".env", ".osa/"]


def init_project(
    *,
    project_dir: Path,
    name: str | None = None,
    force: bool = False,
) -> InitResult:
    """Scaffold a new OSA project directory."""
    project_dir.mkdir(parents=True, exist_ok=True)

    if (project_dir / "osa.yaml").exists() and not force:
        raise InstanceError("Project already initialized. Use --force to overwrite.")

    resolved_name = name or project_dir.name

    # Write osa.yaml
    (project_dir / "osa.yaml").write_text(_OSA_YAML_TEMPLATE.format(name=resolved_name))

    # Write .env with generated secrets
    (project_dir / ".env").write_text(_ENV_TEMPLATE)

    # Create directories
    (project_dir / ".data").mkdir(exist_ok=True)
    (project_dir / ".osa").mkdir(exist_ok=True)

    # Write or append .gitignore
    gitignore_path = project_dir / ".gitignore"
    existing = gitignore_path.read_text() if gitignore_path.exists() else ""
    existing_lines = existing.splitlines()
    to_add = [line for line in _GITIGNORE_LINES if line not in existing_lines]
    if to_add:
        separator = "\n" if existing and not existing.endswith("\n") else ""
        gitignore_path.write_text(existing + separator + "\n".join(to_add) + "\n")

    return InitResult(
        project_dir=project_dir,
        created=[
            ("osa.yaml", "archive configuration"),
            (".env", "secrets and settings (do not commit)"),
            (".data/", "persistent data directory"),
            (".osa/", "CLI state"),
            (".gitignore", "ignores .data/, .env, .osa/"),
        ],
        show_cd=project_dir.resolve() != Path.cwd().resolve(),
    )


def _build_compose_command(
    *,
    project_dir: Path,
    project_name: str,
    source: Path | None = None,
    profiles: list[str] | None = None,
) -> list[str]:
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "--project-directory",
        str(project_dir),
        "-f",
        str(_compose_template_path()),
    ]

    if source is not None:
        dev_override = _write_dev_override(source=source, project_dir=project_dir)
        cmd.extend(["-f", str(dev_override)])

    override_path = project_dir / "docker-compose.override.yml"
    if override_path.exists():
        cmd.extend(["-f", str(override_path)])

    for profile in profiles or []:
        cmd.extend(["--profile", profile])

    cmd.extend(["--env-file", str(project_dir / ".env")])

    return cmd


def _write_dev_override(*, source: Path, project_dir: Path) -> Path:
    source_abs = source.resolve()
    # The image's ENTRYPOINT is /app/scripts/entrypoint.sh and its CMD is the
    # uvicorn invocation. We override CMD to add --reload for hot-reload during
    # source-builds; the entrypoint (migrations + dev admin seed) is shared.
    override = {
        "services": {
            "server": {
                "build": {
                    "context": str(source_abs),
                    "dockerfile": "Dockerfile",
                    "target": "runtime",
                },
                "image": None,
                "command": [
                    "uvicorn",
                    "--factory",
                    "osa.application.api.rest.app:create_app",
                    "--host",
                    "0.0.0.0",
                    "--port",
                    "8000",
                    "--reload",
                ],
                "environment": {
                    "OSA_DEV_MODE": "true",
                },
            }
        }
    }
    dest = project_dir / ".osa" / "docker-compose.dev.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml.dump(override, default_flow_style=False, sort_keys=False))
    return dest


def start_instance(
    *,
    project_dir: Path,
    detach: bool = True,
    source: Path | None = None,
    with_ui: bool = False,
    osa_version: str | None = None,
    ui: UI | None = None,
) -> None:
    ui = ui or UI.create()
    project_name = _read_project_name(project_dir)
    profiles = ["ui"] if with_ui else []

    if osa_version is not None:
        image_version = osa_version
    else:
        with ui.task("Resolving OSA version") as task:
            image_version = fetch_latest_osa_version()
            task.done(detail=image_version)

    cmd = _build_compose_command(
        project_dir=project_dir,
        project_name=project_name,
        source=source,
        profiles=profiles,
    )

    args = [*cmd, "up"]
    if source is not None:
        args.append("--build")
    if detach:
        args.append("-d")

    from osa.cli.link import write_link

    write_link(LOCAL_SERVER_URL, project_dir=project_dir)
    _store_dev_credentials()

    env = {**os.environ, "OSA_IMAGE_VERSION": image_version}

    if not detach:
        # Foreground compose is interactive/streaming — inherit stdio, no UI.
        ui.info(f"Starting OSA {image_version} (foreground, Ctrl-C to stop)")
        result = subprocess.run(args, cwd=project_dir, text=True, env=env)
        if result.returncode != 0:
            raise InstanceError("Failed to start OSA instance.")
        return

    with ui.task("Starting services") as task:
        proc = run_streamed(args, task=task, cwd=project_dir, env=env)
        if proc.returncode != 0:
            raise InstanceError(
                "Failed to start OSA instance",
                cause=tail(proc.output, 30),
                hint="Run `osa logs server --tail 50` for details",
            )
    ui.success(f"OSA {image_version} running", arrow=LOCAL_SERVER_URL)


def stop_instance(*, project_dir: Path, ui: UI | None = None) -> None:
    ui = ui or UI.create()
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    with ui.task("Stopping services") as task:
        proc = run_streamed([*cmd, "down"], task=task, cwd=project_dir)
        if proc.returncode != 0:
            raise InstanceError(
                "Failed to stop OSA instance",
                cause=tail(proc.output, 30),
            )


def instance_logs(
    *,
    project_dir: Path,
    follow: bool = False,
    service: str | None = None,
    tail: int | None = None,
) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    args = [*cmd, "logs"]
    if follow:
        args.append("--follow")
    if tail is not None:
        args.extend(["--tail", str(tail)])
    if service:
        args.append(service)
    return subprocess.run(args, cwd=project_dir, text=True)


def instance_status(*, project_dir: Path) -> list[ComposeService]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    result = subprocess.run(
        [*cmd, "ps", "--format", "json"],
        cwd=project_dir,
        text=True,
        capture_output=True,
    )
    if result.returncode != 0:
        raise InstanceError(
            "Failed to query instance status",
            cause=(result.stderr or result.stdout or "").strip() or None,
        )

    services: list[ComposeService] = []
    for line in (result.stdout or "").strip().splitlines():
        line = line.strip()
        if not line:
            continue
        data = json.loads(line)
        publishers = data.get("Publishers") or []
        ports = ", ".join(
            f"{p['PublishedPort']}->{p['TargetPort']}"
            for p in publishers
            if p.get("PublishedPort")
        )
        services.append(
            ComposeService(
                name=data.get("Service") or data.get("Name", ""),
                state=data.get("State", ""),
                health=data.get("Health", "") or "",
                ports=ports,
            )
        )
    return services
