"""Local OSA instance management — init, start, stop, logs, status."""

from __future__ import annotations

import base64
import hashlib
import hmac
import importlib.resources
import json
import re
import secrets
import subprocess
import time
from pathlib import Path

import yaml

OSA_IMAGE_VERSION = "v0.0.1"


class InstanceError(Exception):
    """Raised when a local instance operation fails."""


def _compose_template_path() -> Path:
    ref = importlib.resources.files("osa.cli.templates").joinpath("docker-compose.yml")
    return Path(str(ref))


def _read_project_name(project_dir: Path) -> str:
    config_path = project_dir / "osa.yaml"
    if not config_path.exists():
        raise InstanceError(
            "osa.yaml not found. Run `osa init` first or cd into your project directory."
        )
    data = yaml.safe_load(config_path.read_text())
    name = data.get("name", project_dir.name)
    return re.sub(r"[^a-z0-9-]", "-", name.lower()).strip("-")


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


DEV_ADMIN_USER_ID = "00000000-0000-7000-8000-0000000000a1"
DEV_JWT_SECRET = (
    "osa-local-dev-jwt-secret-CHANGE-IN-PRODUCTION-not-suitable-for-real-use"
)


def _mint_dev_token() -> str:
    header = json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":"))
    payload = json.dumps(
        {
            "sub": DEV_ADMIN_USER_ID,
            "provider": "local",
            "external_id": "admin@osa.local",
            "aud": "authenticated",
            "iat": int(time.time()),
            "exp": int(time.time()) + 86400 * 365,
            "jti": secrets.token_hex(16),
        },
        separators=(",", ":"),
    )
    header_b64 = _b64url(header.encode())
    payload_b64 = _b64url(payload.encode())
    message = f"{header_b64}.{payload_b64}".encode()
    signature = hmac.new(DEV_JWT_SECRET.encode(), message, hashlib.sha256).digest()
    return f"{header_b64}.{payload_b64}.{_b64url(signature)}"


def _store_dev_credentials(project_dir: Path) -> None:
    """Mint a dev token signed with the well-known dev secret, store it."""
    token = _mint_dev_token()

    from osa.cli.credentials import write_credentials

    write_credentials(
        "http://127.0.0.1:8000",
        access_token=token,
        refresh_token="dev-no-refresh",
    )


_ENV_TEMPLATE = """\
# OSA instance configuration — generated by `osa init`
# Edit as needed. Do not commit to version control.

# === Image Version ===
OSA_IMAGE_VERSION={image_version}

# === Database ===
POSTGRES_USER=postgres
POSTGRES_PASSWORD=osa-local-dev-password-CHANGE-IN-PRODUCTION
POSTGRES_DB=osa

# === Logging ===
LOG_LEVEL=INFO

# === Authentication ===
JWT_SECRET=osa-local-dev-jwt-secret-CHANGE-IN-PRODUCTION-not-suitable-for-real-use

# ORCID credentials (register at https://orcid.org/developer-tools)
ORCID_CLIENT_ID=
ORCID_CLIENT_SECRET=
ORCID_SANDBOX=true
ORCID_ADMINS=[]
"""

_OSA_YAML_TEMPLATE = """\
name: "{name}"
domain: "localhost"

auth:
  providers:
    orcid:
      client_id: ${{ORCID_CLIENT_ID}}
      client_secret: ${{ORCID_CLIENT_SECRET}}
  base_role: "DEPOSITOR"
"""

_GITIGNORE_LINES = [".data/", ".env", ".osa/"]


def init_project(
    *,
    project_dir: Path,
    name: str | None = None,
    force: bool = False,
) -> Path:
    """Scaffold a new OSA project directory.

    Returns the project directory path.
    """
    project_dir.mkdir(parents=True, exist_ok=True)

    if (project_dir / "osa.yaml").exists() and not force:
        raise InstanceError("Project already initialized. Use --force to overwrite.")

    resolved_name = name or project_dir.name

    # Write osa.yaml
    (project_dir / "osa.yaml").write_text(_OSA_YAML_TEMPLATE.format(name=resolved_name))

    # Write .env with generated secrets
    (project_dir / ".env").write_text(
        _ENV_TEMPLATE.format(image_version=OSA_IMAGE_VERSION)
    )

    # Create directories
    (project_dir / ".data").mkdir(exist_ok=True)
    (project_dir / ".osa").mkdir(exist_ok=True)

    # Write or append .gitignore
    gitignore_path = project_dir / ".gitignore"
    existing = gitignore_path.read_text() if gitignore_path.exists() else ""
    existing_lines = existing.splitlines()
    to_add = [line for line in _GITIGNORE_LINES if line not in existing_lines]
    if to_add:
        separator = "\n" if existing and not existing.endswith("\n") else ""
        gitignore_path.write_text(existing + separator + "\n".join(to_add) + "\n")

    print(f"Initialized OSA project in {project_dir}")
    print()
    print("Created:")
    print("  osa.yaml    — archive configuration")
    print("  .env        — secrets and settings (do not commit)")
    print("  .data/      — persistent data directory")
    print("  .osa/       — CLI state")
    print("  .gitignore  — ignores .data/, .env, .osa/")
    print()
    print("Next steps:")
    if project_dir.resolve() != Path.cwd().resolve():
        print(f"  cd {project_dir.name}")
    print("  osa start")

    return project_dir


def _build_compose_command(
    *,
    project_dir: Path,
    project_name: str,
    source: Path | None = None,
    profiles: list[str] | None = None,
) -> list[str]:
    cmd = [
        "docker",
        "compose",
        "--project-name",
        project_name,
        "--project-directory",
        str(project_dir),
        "-f",
        str(_compose_template_path()),
    ]

    if source is not None:
        dev_override = _write_dev_override(source=source, project_dir=project_dir)
        cmd.extend(["-f", str(dev_override)])

    override_path = project_dir / "docker-compose.override.yml"
    if override_path.exists():
        cmd.extend(["-f", str(override_path)])

    for profile in profiles or []:
        cmd.extend(["--profile", profile])

    cmd.extend(["--env-file", str(project_dir / ".env")])

    return cmd


def _write_dev_override(*, source: Path, project_dir: Path) -> Path:
    source_abs = source.resolve()
    override = {
        "services": {
            "server": {
                "build": {
                    "context": str(source_abs),
                    "dockerfile": "Dockerfile",
                },
                "image": None,
                "environment": {
                    "OSA_DEV_MODE": "true",
                },
            }
        }
    }
    dest = project_dir / ".osa" / "docker-compose.dev.yml"
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(yaml.dump(override, default_flow_style=False, sort_keys=False))
    return dest


def start_instance(
    *,
    project_dir: Path,
    detach: bool = True,
    source: Path | None = None,
    with_ui: bool = False,
) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    profiles = ["ui"] if with_ui else []

    cmd = _build_compose_command(
        project_dir=project_dir,
        project_name=project_name,
        source=source,
        profiles=profiles,
    )

    args = [*cmd, "up"]
    if source is not None:
        args.append("--build")
    if detach:
        args.append("-d")

    from osa.cli.link import write_link

    write_link("http://127.0.0.1:8000", project_dir=project_dir)
    _store_dev_credentials(project_dir)

    result = subprocess.run(args, cwd=project_dir, text=True)
    if result.returncode != 0:
        raise InstanceError("Failed to start OSA instance.")
    return result


def stop_instance(*, project_dir: Path) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    result = subprocess.run([*cmd, "down"], cwd=project_dir, text=True)
    if result.returncode != 0:
        raise InstanceError("Failed to stop OSA instance.")
    return result


def instance_logs(
    *,
    project_dir: Path,
    follow: bool = False,
    service: str | None = None,
    tail: int | None = None,
) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    args = [*cmd, "logs"]
    if follow:
        args.append("--follow")
    if tail is not None:
        args.extend(["--tail", str(tail)])
    if service:
        args.append(service)
    return subprocess.run(args, cwd=project_dir, text=True)


def instance_status(*, project_dir: Path) -> subprocess.CompletedProcess[str]:
    project_name = _read_project_name(project_dir)
    cmd = _build_compose_command(project_dir=project_dir, project_name=project_name)
    return subprocess.run([*cmd, "ps"], cwd=project_dir, text=True)
